server:
  port: 8084

spring:
  application:
    name: APIGATEWAY


  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**


        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
eureka:
        instance:
          prefer-ip-address: true
        client:
            fetch-registry: true
            register-with-eureka: true
            service-url:
              defaultZone: http://localhost:8761/eureka/

#           https://dev-98806091-admin.okta.com/admin/oauth2/as
#https://dev-98806091-admin.okta.com/admin/oauth2/as/ausbcn847kYurWPpa5d7#scopes
#okta configuration for api gateway
#
okta:
  oauth2:
    issuer: https://dev-98806091.okta.com/oauth2/default
    audience: api://default
    client-id: 0oabcwigeq8s2DvYp5d7
    client-secret: QSNKyl2Oyg8pcxHtBU4P7xHO0aBs5llNh6yyH2XDxYKAxDoAFUz_n3QMJwSP4zrX
    scopes: openid, profile, email , offline_access




