server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/avk-007/microService-ConfigServer.git
          clone-on-start: true
