server:
  port: 8761 # Port on which Eureka Server will run

eureka:
  client:
    register-with-eureka: false # The Eureka Server itself won't register with itself
    fetch-registry: false # The Eureka Server won't try to fetch registry information from itself
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Default URL for registering and fetching services