server:
  port: 8082
spring:
  application:
    name: hotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8085
#  profiles:
#    active: dev
#    eureka:
#      instance:
#        prefer-ip-address: true
#        client:
#          fetch-registry: true
#          register-with-eureka: true
#          service-url:
#            defaultZone: http://localhost:8761/eureka/
okta:
  oauth2:
    issuer: https://dev-98806091.okta.com/oauth2/default
    audience: api://default
